/**
 * Explicitly audited server tests that may share a module cache.
 *
 * These exercise local transforms, parsers, immutable schemas, or state created
 * per test. They do not mock modules, replace globals, mutate the environment,
 * use process listeners, open native resources, or exercise mutable module-level
 * application state. Keep new/integration tests isolated by default; additions
 * require inspecting test setup and transitive runtime imports, then running
 * this group with isolation disabled and shuffled file/test order.
 *
 * Class-only timing tests instantiate ComputerTurnTimings with injected clocks
 * and emitters; they never call its module-level singleton or environment flags.
 */
export const SERVER_PURE_TEST_FILES = [
  "src/agentControl/Mcp/transportGuard.test.ts",
  "src/agentControl/planDigest.test.ts",
  "src/agentControl/transitions.test.ts",
  "src/computer/computerTurnTiming.test.ts",
  "src/computer/tools/computerBrowserEffect.test.ts",
  "src/computer/tools/computerGuidance.test.ts",
  "src/computer/tools/computerProgressGuard.test.ts",
  "src/computer/tools/toolGuidanceCadence.test.ts",
  "src/computer/utf8Truncation.test.ts",
  "src/device/deviceFrameTransport.test.ts",
  "src/device/helperCapabilities.test.ts",
  "src/device/uiTreeTargeting.test.ts",
  "src/hubConnector/HubEnrollmentLabel.test.ts",
  "src/hubConnector/ReconnectPolicy.test.ts",
  "src/imageMime.test.ts",
  "src/observability/RollingDurationWindow.test.ts",
  "src/orchestration/ActivityPayloadProjection.test.ts",
  "src/orchestration/ThreadBackgroundLiveness.test.ts",
  "src/orchestration/activityDataCap.test.ts",
  "src/orchestration/commandInvariants.test.ts",
  "src/orchestration/contextHandoff/ContextHandoffBuilder.test.ts",
  "src/orchestration/contextHandoff/ContextHandoffInspection.test.ts",
  "src/orchestration/contextHandoff/ContextHandoffRenderer.test.ts",
  "src/orchestration/contextWindowActivities.test.ts",
  "src/orchestration/decider.claudeResumeReview.test.ts",
  "src/orchestration/decider.contextHandoff.test.ts",
  "src/orchestration/decider.delete.test.ts",
  "src/orchestration/decider.goal.test.ts",
  "src/orchestration/decider.import.test.ts",
  "src/orchestration/decider.projectScripts.test.ts",
  "src/orchestration/decider.settlement.test.ts",
  "src/orchestration/decider.steer.test.ts",
  "src/orchestration/decider.tokenMode.test.ts",
  "src/orchestration/projector.test.ts",
  "src/orchestration/threadHistoryCursor.test.ts",
  "src/orchestration/threadShellSummaryProjection.test.ts",
  "src/project/worktreeCheckoutPaths.test.ts",
  "src/provider/claudeCacheObservation.test.ts",
  "src/provider/cliVersion.test.ts",
  "src/provider/codexOptionalQuestions.test.ts",
  "src/provider/contextCompactionPolicy.test.ts",
  "src/provider/goalMode.test.ts",
  "src/sourceControl/azureDevOpsPullRequests.test.ts",
  "src/sourceControl/azureDevOpsWorkItems.test.ts",
  "src/sourceControl/bitbucketIssues.test.ts",
  "src/sourceControl/bitbucketPullRequests.test.ts",
  "src/sourceControl/forgejoIssues.test.ts",
  "src/sourceControl/forgejoPullRequests.test.ts",
  "src/sourceControl/gitHubIssueCreate.test.ts",
  "src/sourceControl/gitHubIssues.test.ts",
  "src/sourceControl/gitHubPullRequestStacks.test.ts",
  "src/sourceControl/gitHubPullRequests.test.ts",
  "src/sourceControl/gitLabIssues.test.ts",
  "src/sourceControl/gitLabMergeRequests.test.ts",
  "src/terminal/historyBuffer.test.ts",
  "src/threadPriority/threadPriorityPolicy.test.ts",
  "src/usage/claudeTranscript.test.ts",
  "src/usage/codexTranscript.test.ts",
  "src/usage/usageAggregation.test.ts",
  "src/usage/usagePricing.test.ts",
  "src/usage/usageScanCache.test.ts",
  "src/ws/RpcAccessPolicy.test.ts",
] as const;
