/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as PairRouteImport } from './routes/pair'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsDiagnosticsRouteImport } from './routes/_settings.diagnostics'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as NativeAuthorizeHandoffIdRouteImport } from './routes/native.authorize.$handoffId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/_settings/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const NativeAuthorizeHandoffIdRoute =
  NativeAuthorizeHandoffIdRouteImport.update({
    id: '/native/authorize/$handoffId',
    path: '/native/authorize/$handoffId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/workspaces': typeof WorkspacesRoute
  '/diagnostics': typeof SettingsDiagnosticsRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/native/authorize/$handoffId': typeof NativeAuthorizeHandoffIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/workspaces': typeof WorkspacesRoute
  '/diagnostics': typeof SettingsDiagnosticsRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/native/authorize/$handoffId': typeof NativeAuthorizeHandoffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/workspaces': typeof WorkspacesRoute
  '/_settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/native/authorize/$handoffId': typeof NativeAuthorizeHandoffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/pull-requests'
    | '/settings'
    | '/statistics'
    | '/workspaces'
    | '/diagnostics'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/native/authorize/$handoffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/pull-requests'
    | '/settings'
    | '/statistics'
    | '/workspaces'
    | '/diagnostics'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/native/authorize/$handoffId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/pull-requests'
    | '/settings'
    | '/statistics'
    | '/workspaces'
    | '/_settings/diagnostics'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/native/authorize/$handoffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  PullRequestsRoute: typeof PullRequestsRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  NativeAuthorizeHandoffIdRoute: typeof NativeAuthorizeHandoffIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_settings/diagnostics': {
      id: '/_settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/native/authorize/$handoffId': {
      id: '/native/authorize/$handoffId'
      path: '/native/authorize/$handoffId'
      fullPath: '/native/authorize/$handoffId'
      preLoaderRoute: typeof NativeAuthorizeHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  PullRequestsRoute: PullRequestsRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  WorkspacesRoute: WorkspacesRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  NativeAuthorizeHandoffIdRoute: NativeAuthorizeHandoffIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
