export const DESKTOP_WORKSPACE_IPC = {
  getState: "desktop:workspace-get-state",
  refreshCatalog: "desktop:workspace-refresh-catalog",
  renameDevice: "desktop:workspace-rename-device",
  publishSnapshot: "desktop:workspace-publish-snapshot",
  retainScope: "desktop:workspace-retain-scope",
  renewScope: "desktop:workspace-renew-scope",
  releaseScope: "desktop:workspace-release-scope",
  setBackgrounded: "desktop:workspace-set-backgrounded",
  purgeCache: "desktop:workspace-purge-cache",
  beginVerification: "desktop:workspace-begin-verification",
  cancelVerification: "desktop:workspace-cancel-verification",
  verifyApproval: "desktop:workspace-verify-approval",
  stateChanged: "desktop:workspace-state-changed",
  connectionCommand: "desktop:workspace-connection-command",
  prepareTransport: "desktop:workspace-prepare-transport",
  activateTransport: "desktop:workspace-activate-transport",
  sendTransport: "desktop:workspace-send-transport",
  closeTransport: "desktop:workspace-close-transport",
  reportConnection: "desktop:workspace-report-connection",
  transportEvent: "desktop:workspace-transport-event",
} as const;
