export {
  ThreadSnoozedPayload,
  ThreadUnsnoozedPayload,
  ThreadUsageLimitClearedPayload,
  ThreadUsageLimitSetPayload,
} from "@ryco/contracts";
import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectAvatarSetPayload as ContractsProjectAvatarSetPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadTokenModeSetPayload as ContractsThreadTokenModeSetPayloadSchema,
  ThreadGoalUpdatedPayload as ContractsThreadGoalUpdatedPayloadSchema,
  ThreadGoalClearedPayload as ContractsThreadGoalClearedPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadAttachedToWorktreePayload as ContractsThreadAttachedToWorktreePayloadSchema,
  ThreadStatusBucketOverriddenPayload as ContractsThreadStatusBucketOverriddenPayloadSchema,
  WorktreeArchivedPayload as ContractsWorktreeArchivedPayloadSchema,
  WorktreeCreatedPayload as ContractsWorktreeCreatedPayloadSchema,
  WorktreeDeletedPayload as ContractsWorktreeDeletedPayloadSchema,
  WorktreeManualPositionSetPayload as ContractsWorktreeManualPositionSetPayloadSchema,
  WorktreeMetaUpdatedPayload as ContractsWorktreeMetaUpdatedPayloadSchema,
  WorktreeRestoredPayload as ContractsWorktreeRestoredPayloadSchema,
  WorktreeSourceControlStateUpdatedPayload as ContractsWorktreeSourceControlStateUpdatedPayloadSchema,
} from "@ryco/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectAvatarSetPayload = ContractsProjectAvatarSetPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadTokenModeSetPayload = ContractsThreadTokenModeSetPayloadSchema;
export const ThreadGoalUpdatedPayload = ContractsThreadGoalUpdatedPayloadSchema;
export const ThreadGoalClearedPayload = ContractsThreadGoalClearedPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const ThreadAttachedToWorktreePayload = ContractsThreadAttachedToWorktreePayloadSchema;
export const ThreadStatusBucketOverriddenPayload =
  ContractsThreadStatusBucketOverriddenPayloadSchema;
export const WorktreeCreatedPayload = ContractsWorktreeCreatedPayloadSchema;
export const WorktreeArchivedPayload = ContractsWorktreeArchivedPayloadSchema;
export const WorktreeMetaUpdatedPayload = ContractsWorktreeMetaUpdatedPayloadSchema;
export const WorktreeSourceControlStateUpdatedPayload =
  ContractsWorktreeSourceControlStateUpdatedPayloadSchema;
export const WorktreeRestoredPayload = ContractsWorktreeRestoredPayloadSchema;
export const WorktreeDeletedPayload = ContractsWorktreeDeletedPayloadSchema;
export const WorktreeManualPositionSetPayload = ContractsWorktreeManualPositionSetPayloadSchema;
