import {
  AGENT_CONTROL_WS_METHODS,
  CONTEXT_HANDOFF_WS_METHODS,
  DEVICE_WS_METHODS,
  ORCHESTRATION_WS_METHODS,
  WS_METHODS,
  type RelayEffectiveRole,
} from "@ryco/contracts";

export type RpcMethod =
  | (typeof WS_METHODS)[keyof typeof WS_METHODS]
  | (typeof ORCHESTRATION_WS_METHODS)[keyof typeof ORCHESTRATION_WS_METHODS]
  | (typeof CONTEXT_HANDOFF_WS_METHODS)[keyof typeof CONTEXT_HANDOFF_WS_METHODS]
  | (typeof DEVICE_WS_METHODS)[keyof typeof DEVICE_WS_METHODS]
  | (typeof AGENT_CONTROL_WS_METHODS)[keyof typeof AGENT_CONTROL_WS_METHODS];

export type RpcAccess = RelayEffectiveRole | "authenticated" | "direct_owner";

export const RPC_ACCESS_POLICY = {
  [WS_METHODS.serverGetProjectPreferences]: "viewer",
  [WS_METHODS.storageScan]: "owner",
  [WS_METHODS.storagePreview]: "owner",
  [WS_METHODS.storageExecute]: "owner",
  [WS_METHODS.sessionImportSources]: "owner",
  [WS_METHODS.sessionImportReconcile]: "owner",
  [WS_METHODS.sessionImportAdopt]: "owner",
  [WS_METHODS.sessionImportDiscover]: "owner",
  [WS_METHODS.sessionImportRun]: "owner",
  [AGENT_CONTROL_WS_METHODS.automationCentre]: "owner",
  [AGENT_CONTROL_WS_METHODS.automationCommand]: "owner",
  [DEVICE_WS_METHODS.read]: "viewer",
  [DEVICE_WS_METHODS.subscribeEvents]: "viewer",
  [DEVICE_WS_METHODS.lifecycle]: "owner",
  [DEVICE_WS_METHODS.input]: "owner",
  [DEVICE_WS_METHODS.app]: "owner",
  [DEVICE_WS_METHODS.recording]: "owner",
  // Agent Control approval decisions authorize agent-requested mutations
  // and the queue exposes prompt summaries and target metadata, so the
  // whole surface is owner-only — including reads and the push stream.
  [AGENT_CONTROL_WS_METHODS.acceptProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.getProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.listProposals]: "owner",
  [AGENT_CONTROL_WS_METHODS.rejectProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.subscribeProposals]: "owner",
  [AGENT_CONTROL_WS_METHODS.listIntegrations]: "owner",
  [AGENT_CONTROL_WS_METHODS.createIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.updateIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.resumeIntegrationPairing]: "owner",
  [AGENT_CONTROL_WS_METHODS.revokeIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.deleteIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.listMcpInstallations]: "owner",
  [AGENT_CONTROL_WS_METHODS.connectMcpInstallation]: "owner",
  [AGENT_CONTROL_WS_METHODS.repairMcpInstallation]: "owner",
  [AGENT_CONTROL_WS_METHODS.disconnectMcpInstallation]: "owner",
  [WS_METHODS.atlassianDisconnect]: "owner",
  [WS_METHODS.atlassianGetProjectLink]: "owner",
  [WS_METHODS.atlassianListConnections]: "owner",
  [WS_METHODS.atlassianListResources]: "owner",
  [WS_METHODS.atlassianRefresh]: "owner",
  [WS_METHODS.atlassianSaveManualBitbucketToken]: "owner",
  [WS_METHODS.atlassianSaveManualJiraToken]: "owner",
  [WS_METHODS.atlassianSaveProjectLink]: "owner",
  [WS_METHODS.atlassianStartOAuth]: "owner",
  [WS_METHODS.chatAttachmentsCreateFileUpload]: "operator",
  [WS_METHODS.chatAttachmentsReadChunk]: "operator",
  [WS_METHODS.filesystemBrowse]: "operator",
  [WS_METHODS.gitArchiveWorktree]: "operator",
  [WS_METHODS.gitCreateWorktreeForProject]: "operator",
  [WS_METHODS.gitDeleteWorktree]: "operator",
  [WS_METHODS.lifecycleListWorkspaces]: "operator",
  [WS_METHODS.lifecyclePreviewWorkspace]: "operator",
  [WS_METHODS.lifecycleApplyWorkspace]: "operator",
  [WS_METHODS.lifecycleSuggestions]: "operator",
  [WS_METHODS.lifecycleListTrash]: "viewer",
  [WS_METHODS.gitFindWorktreeForOrigin]: "operator",
  [WS_METHODS.gitPreparePullRequestThread]: "operator",
  [WS_METHODS.gitResolvePullRequest]: "operator",
  [WS_METHODS.gitRestoreWorktree]: "operator",
  [WS_METHODS.gitRunStackedAction]: "operator",
  [WS_METHODS.keybindingsReplaceCustom]: "owner",
  [WS_METHODS.mcpListServers]: "owner",
  [WS_METHODS.mcpListWorkspaces]: "owner",
  [WS_METHODS.mcpReloadServers]: "owner",
  [WS_METHODS.mcpRemoveServer]: "owner",
  [WS_METHODS.mcpSetServerEnabled]: "owner",
  [WS_METHODS.mcpStartOauthLogin]: "owner",
  [WS_METHODS.mcpUpsertServer]: "owner",
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: "operator",
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: "viewer",
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: "viewer",
  // File-content reads match projectsReadFile/filesystemBrowse: operator,
  // not viewer — scripts and task outputs can carry prompts and secrets.
  [ORCHESTRATION_WS_METHODS.getTaskOutput]: "operator",
  [ORCHESTRATION_WS_METHODS.getThreadHistoryPage]: "viewer",
  [ORCHESTRATION_WS_METHODS.getThreadWindow]: "viewer",
  [ORCHESTRATION_WS_METHODS.getWorkflowScript]: "operator",
  [ORCHESTRATION_WS_METHODS.stopBackgroundTask]: "operator",
  [ORCHESTRATION_WS_METHODS.replayEvents]: "viewer",
  [ORCHESTRATION_WS_METHODS.replayEventsPage]: "viewer",
  [ORCHESTRATION_WS_METHODS.searchThreadMessages]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeShell]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeThread]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeThreadWindow]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.getInspectionSummary]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.listInspectionEntries]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.readRawPayloadChunk]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.readExportChunk]: "viewer",
  [WS_METHODS.projectsAdd]: "operator",
  [WS_METHODS.projectsInitializeGit]: "operator",
  [WS_METHODS.projectsList]: "viewer",
  [WS_METHODS.projectsListEntries]: "operator",
  [WS_METHODS.projectsReadFile]: "operator",
  [WS_METHODS.projectsReadIcon]: "viewer",
  [WS_METHODS.projectsReadFileBinary]: "operator",
  [WS_METHODS.projectsRemove]: "operator",
  [WS_METHODS.projectsSearchEntries]: "operator",
  [WS_METHODS.projectsStageFileReference]: "operator",
  [WS_METHODS.projectsWriteFile]: "operator",
  [WS_METHODS.serverCheckOpinionatedPlugins]: "owner",
  [WS_METHODS.serverDiscoverSourceControl]: "owner",
  [WS_METHODS.serverGetAdvertisedEndpoints]: "viewer",
  [WS_METHODS.serverGetConfig]: "viewer",
  [WS_METHODS.serverGetDiagnosticsMetrics]: "owner",
  [WS_METHODS.serverGetDiagnosticsSnapshot]: "owner",
  [WS_METHODS.serverSignalDiagnosticProcess]: "owner",
  [WS_METHODS.serverGetResourceTelemetryHistory]: "owner",
  [WS_METHODS.serverRetryResourceTelemetry]: "owner",
  [WS_METHODS.serverGetSettings]: "viewer",
  [WS_METHODS.serverGetStatistics]: "owner",
  [WS_METHODS.serverGetUsageSummary]: "owner",
  [WS_METHODS.serverInstallOpinionatedPlugin]: "owner",
  [WS_METHODS.serverListOpinionatedPlugins]: "owner",
  [WS_METHODS.serverSearchAcpRegistry]: "viewer",
  [WS_METHODS.serverInstallAcpRegistry]: "owner",
  [WS_METHODS.serverGetAcpRegistryAuthMethods]: "owner",
  [WS_METHODS.serverAuthenticateAcpRegistry]: "owner",
  [WS_METHODS.serverReadCodexResetCredits]: "owner",
  [WS_METHODS.serverConsumeCodexResetCredit]: "owner",
  [WS_METHODS.serverListLocalTasks]: "owner",
  [WS_METHODS.serverGetLocalTask]: "owner",
  [WS_METHODS.serverCreateLocalTask]: "owner",
  [WS_METHODS.serverUpdateLocalTask]: "owner",
  [WS_METHODS.serverDeleteLocalTask]: "owner",
  [WS_METHODS.serverDelegateLocalTask]: "owner",
  [WS_METHODS.serverGetDailyRecap]: "owner",
  [WS_METHODS.serverRefreshProviders]: "owner",
  [WS_METHODS.serverUpdateProvider]: "owner",
  [WS_METHODS.serverUpdateSettings]: "owner",
  [WS_METHODS.serverUpsertKeybinding]: "owner",
  [WS_METHODS.shellOpenInEditor]: "operator",
  [WS_METHODS.sourceControlAddChangeRequestComment]: "operator",
  [WS_METHODS.sourceControlAddChangeRequestCommentReaction]: "operator",
  [WS_METHODS.sourceControlAddIssueComment]: "operator",
  [WS_METHODS.sourceControlAddIssueCommentReaction]: "operator",
  [WS_METHODS.sourceControlCloneRepository]: "operator",
  [WS_METHODS.sourceControlCreateIssue]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestDetail]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestFilesViewed]: "operator",
  [WS_METHODS.sourceControlSetChangeRequestFileViewed]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestDiff]: "operator",
  [WS_METHODS.sourceControlGetIssue]: "operator",
  [WS_METHODS.sourceControlGetWorkflowJobLog]: "operator",
  [WS_METHODS.sourceControlGetWorkflowRunJobs]: "operator",
  [WS_METHODS.sourceControlListChangeRequests]: "operator",
  [WS_METHODS.sourceControlListIssueAssignees]: "operator",
  [WS_METHODS.sourceControlListIssueLabels]: "operator",
  [WS_METHODS.sourceControlListIssues]: "operator",
  [WS_METHODS.sourceControlListWorkflowRuns]: "operator",
  [WS_METHODS.sourceControlLookupRepository]: "operator",
  [WS_METHODS.sourceControlMergeChangeRequest]: "operator",
  [WS_METHODS.sourceControlPublishRepository]: "operator",
  [WS_METHODS.sourceControlRerunWorkflow]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestActivity]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestFileContents]: "operator",
  [WS_METHODS.sourceControlSubmitChangeRequestReview]: "operator",
  [WS_METHODS.sourceControlReplyToReviewThread]: "operator",
  [WS_METHODS.sourceControlSetReviewThreadResolved]: "operator",
  [WS_METHODS.sourceControlUpdateChangeRequestComment]: "operator",
  [WS_METHODS.sourceControlUpdateChangeRequest]: "operator",
  [WS_METHODS.sourceControlCreateChangeRequest]: "operator",
  [WS_METHODS.sourceControlLinkWorktreePullRequest]: "operator",
  [WS_METHODS.sourceControlDismissWorktreePullRequest]: "operator",
  [WS_METHODS.sourceControlSearchChangeRequests]: "operator",
  [WS_METHODS.sourceControlSearchIssues]: "operator",
  [WS_METHODS.sourceControlSearchRepositories]: "operator",
  [WS_METHODS.subscribeAuthAccess]: "direct_owner",
  [WS_METHODS.subscribeServerConfig]: "viewer",
  [WS_METHODS.subscribeServerLifecycle]: "viewer",
  [WS_METHODS.subscribeTerminalEvents]: "operator",
  [WS_METHODS.subscribeVcsStatus]: "operator",
  [WS_METHODS.terminalClear]: "operator",
  [WS_METHODS.terminalClose]: "operator",
  [WS_METHODS.terminalOpen]: "operator",
  [WS_METHODS.terminalResize]: "operator",
  [WS_METHODS.terminalRestart]: "operator",
  [WS_METHODS.terminalWrite]: "operator",
  [WS_METHODS.textGenerationAskSideQuestion]: "operator",
  [WS_METHODS.textGenerationCancelSideQuestion]: "operator",
  [WS_METHODS.textGenerationGenerateBranchName]: "operator",
  [WS_METHODS.textGenerationGenerateIssueContent]: "operator",
  [WS_METHODS.threadPriorityEnsureCurrent]: "operator",
  [WS_METHODS.searchThreadMessages]: "owner",
  [WS_METHODS.threadsSetManualBucket]: "operator",
  [WS_METHODS.threadsSetManualPosition]: "operator",
  [WS_METHODS.vcsCreateRef]: "operator",
  [WS_METHODS.vcsCreateWorktree]: "operator",
  [WS_METHODS.vcsInit]: "operator",
  [WS_METHODS.vcsListRefs]: "operator",
  [WS_METHODS.vcsReadLineBlame]: "operator",
  [WS_METHODS.vcsReadLocalChanges]: "operator",
  [WS_METHODS.vcsApplyIndexPatch]: "operator",
  [WS_METHODS.vcsReadComparison]: "operator",
  [WS_METHODS.vcsPull]: "operator",
  [WS_METHODS.vcsRefreshStatus]: "operator",
  [WS_METHODS.vcsRemoveWorktree]: "operator",
  [WS_METHODS.vcsSwitchRef]: "operator",
  [WS_METHODS.workItemsAddComment]: "operator",
  [WS_METHODS.workItemsEditComment]: "operator",
  [WS_METHODS.workItemsGet]: "viewer",
  [WS_METHODS.workItemsList]: "viewer",
  [WS_METHODS.workItemsListProjects]: "viewer",
  [WS_METHODS.workItemsListTransitions]: "viewer",
  [WS_METHODS.workItemsSearch]: "viewer",
  [WS_METHODS.workItemsTransition]: "operator",
  [WS_METHODS.workItemsUpdate]: "operator",
  [WS_METHODS.worktreesSetManualPosition]: "operator",
} as const satisfies Record<RpcMethod, RpcAccess>;

export function rpcAccessFor(method: string): RpcAccess {
  if (!Object.hasOwn(RPC_ACCESS_POLICY, method)) {
    throw new Error("RPC method has no explicit access classification.");
  }
  return RPC_ACCESS_POLICY[method as RpcMethod];
}

/**
 * What a lost response means for each method — an effect classification, kept
 * apart from the access tiers above on purpose: file, VCS, and source-control
 * reads are operator-tier, so a tier says nothing about whether a request
 * changed anything.
 *
 * - `read` observes node state, or refreshes derived state the node would
 *   regenerate anyway. Losing or repeating one is harmless, so a dropped relay
 *   never leaves its delivery uncertain.
 * - `receipted` changes node state at most once per client-supplied id, and the
 *   node enforces that with a persisted receipt it consults before executing.
 *   Only these may be replayed — unchanged, id included — after a reconnect.
 * - `mutation` is everything else. Its delivery is uncertain whenever the relay
 *   drops before a response, and it is never replayed automatically.
 */
export type RpcDeliveryEffect = "read" | "receipted" | "mutation";

export const RPC_DELIVERY_EFFECT_POLICY = {
  [WS_METHODS.serverGetProjectPreferences]: "read",
  [WS_METHODS.storageScan]: "read",
  [WS_METHODS.storagePreview]: "read",
  [WS_METHODS.storageExecute]: "mutation",
  [WS_METHODS.sessionImportSources]: "read",
  [WS_METHODS.sessionImportReconcile]: "mutation",
  [WS_METHODS.sessionImportAdopt]: "mutation",
  [WS_METHODS.sessionImportDiscover]: "read",
  [WS_METHODS.sessionImportRun]: "mutation",
  [AGENT_CONTROL_WS_METHODS.automationCentre]: "read",
  [AGENT_CONTROL_WS_METHODS.automationCommand]: "mutation",
  [DEVICE_WS_METHODS.read]: "read",
  [DEVICE_WS_METHODS.subscribeEvents]: "read",
  [DEVICE_WS_METHODS.lifecycle]: "mutation",
  [DEVICE_WS_METHODS.input]: "mutation",
  [DEVICE_WS_METHODS.app]: "mutation",
  [DEVICE_WS_METHODS.recording]: "mutation",
  [AGENT_CONTROL_WS_METHODS.acceptProposal]: "mutation",
  [AGENT_CONTROL_WS_METHODS.getProposal]: "read",
  [AGENT_CONTROL_WS_METHODS.listProposals]: "read",
  [AGENT_CONTROL_WS_METHODS.rejectProposal]: "mutation",
  [AGENT_CONTROL_WS_METHODS.subscribeProposals]: "read",
  [AGENT_CONTROL_WS_METHODS.listIntegrations]: "read",
  [AGENT_CONTROL_WS_METHODS.createIntegration]: "mutation",
  [AGENT_CONTROL_WS_METHODS.updateIntegration]: "mutation",
  [AGENT_CONTROL_WS_METHODS.resumeIntegrationPairing]: "mutation",
  [AGENT_CONTROL_WS_METHODS.revokeIntegration]: "mutation",
  [AGENT_CONTROL_WS_METHODS.deleteIntegration]: "mutation",
  [AGENT_CONTROL_WS_METHODS.listMcpInstallations]: "read",
  [AGENT_CONTROL_WS_METHODS.connectMcpInstallation]: "mutation",
  [AGENT_CONTROL_WS_METHODS.repairMcpInstallation]: "mutation",
  [AGENT_CONTROL_WS_METHODS.disconnectMcpInstallation]: "mutation",
  [WS_METHODS.atlassianDisconnect]: "mutation",
  [WS_METHODS.atlassianGetProjectLink]: "read",
  [WS_METHODS.atlassianListConnections]: "read",
  [WS_METHODS.atlassianListResources]: "read",
  // Refreshing rotates the stored OAuth credential.
  [WS_METHODS.atlassianRefresh]: "mutation",
  [WS_METHODS.atlassianSaveManualBitbucketToken]: "mutation",
  [WS_METHODS.atlassianSaveManualJiraToken]: "mutation",
  [WS_METHODS.atlassianSaveProjectLink]: "mutation",
  [WS_METHODS.atlassianStartOAuth]: "mutation",
  [WS_METHODS.chatAttachmentsCreateFileUpload]: "mutation",
  [WS_METHODS.chatAttachmentsReadChunk]: "read",
  [WS_METHODS.filesystemBrowse]: "read",
  [WS_METHODS.gitArchiveWorktree]: "mutation",
  [WS_METHODS.gitCreateWorktreeForProject]: "mutation",
  [WS_METHODS.gitDeleteWorktree]: "mutation",
  [WS_METHODS.lifecycleListWorkspaces]: "read",
  [WS_METHODS.lifecyclePreviewWorkspace]: "read",
  [WS_METHODS.lifecycleApplyWorkspace]: "mutation",
  [WS_METHODS.lifecycleSuggestions]: "read",
  [WS_METHODS.lifecycleListTrash]: "read",
  [WS_METHODS.gitFindWorktreeForOrigin]: "read",
  [WS_METHODS.gitPreparePullRequestThread]: "mutation",
  [WS_METHODS.gitResolvePullRequest]: "read",
  [WS_METHODS.gitRestoreWorktree]: "mutation",
  [WS_METHODS.gitRunStackedAction]: "mutation",
  [WS_METHODS.keybindingsReplaceCustom]: "mutation",
  [WS_METHODS.mcpListServers]: "read",
  [WS_METHODS.mcpListWorkspaces]: "read",
  // Reloading restarts server processes that live sessions may be using.
  [WS_METHODS.mcpReloadServers]: "mutation",
  [WS_METHODS.mcpRemoveServer]: "mutation",
  [WS_METHODS.mcpSetServerEnabled]: "mutation",
  [WS_METHODS.mcpStartOauthLogin]: "mutation",
  [WS_METHODS.mcpUpsertServer]: "mutation",
  // The node answers a repeated commandId from its command receipt.
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: "receipted",
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: "read",
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: "read",
  [ORCHESTRATION_WS_METHODS.getTaskOutput]: "read",
  [ORCHESTRATION_WS_METHODS.getThreadHistoryPage]: "read",
  [ORCHESTRATION_WS_METHODS.getThreadWindow]: "read",
  [ORCHESTRATION_WS_METHODS.getWorkflowScript]: "read",
  [ORCHESTRATION_WS_METHODS.stopBackgroundTask]: "mutation",
  [ORCHESTRATION_WS_METHODS.replayEvents]: "read",
  [ORCHESTRATION_WS_METHODS.replayEventsPage]: "read",
  [ORCHESTRATION_WS_METHODS.searchThreadMessages]: "read",
  [ORCHESTRATION_WS_METHODS.subscribeShell]: "read",
  [ORCHESTRATION_WS_METHODS.subscribeThread]: "read",
  [ORCHESTRATION_WS_METHODS.subscribeThreadWindow]: "read",
  [CONTEXT_HANDOFF_WS_METHODS.getInspectionSummary]: "read",
  [CONTEXT_HANDOFF_WS_METHODS.listInspectionEntries]: "read",
  [CONTEXT_HANDOFF_WS_METHODS.readRawPayloadChunk]: "read",
  [CONTEXT_HANDOFF_WS_METHODS.readExportChunk]: "read",
  [WS_METHODS.projectsAdd]: "mutation",
  [WS_METHODS.projectsInitializeGit]: "mutation",
  [WS_METHODS.projectsList]: "read",
  [WS_METHODS.projectsListEntries]: "read",
  [WS_METHODS.projectsReadFile]: "read",
  [WS_METHODS.projectsReadIcon]: "read",
  [WS_METHODS.projectsReadFileBinary]: "read",
  [WS_METHODS.projectsRemove]: "mutation",
  [WS_METHODS.projectsSearchEntries]: "read",
  [WS_METHODS.projectsStageFileReference]: "mutation",
  [WS_METHODS.projectsWriteFile]: "mutation",
  [WS_METHODS.serverCheckOpinionatedPlugins]: "read",
  [WS_METHODS.serverDiscoverSourceControl]: "read",
  [WS_METHODS.serverGetAdvertisedEndpoints]: "read",
  [WS_METHODS.serverGetConfig]: "read",
  [WS_METHODS.serverGetDiagnosticsMetrics]: "read",
  [WS_METHODS.serverGetDiagnosticsSnapshot]: "read",
  [WS_METHODS.serverSignalDiagnosticProcess]: "mutation",
  [WS_METHODS.serverGetResourceTelemetryHistory]: "read",
  [WS_METHODS.serverRetryResourceTelemetry]: "mutation",
  [WS_METHODS.serverGetSettings]: "read",
  [WS_METHODS.serverGetStatistics]: "read",
  [WS_METHODS.serverGetUsageSummary]: "read",
  [WS_METHODS.serverInstallOpinionatedPlugin]: "mutation",
  [WS_METHODS.serverListOpinionatedPlugins]: "read",
  [WS_METHODS.serverSearchAcpRegistry]: "read",
  [WS_METHODS.serverInstallAcpRegistry]: "mutation",
  [WS_METHODS.serverGetAcpRegistryAuthMethods]: "read",
  [WS_METHODS.serverAuthenticateAcpRegistry]: "mutation",
  [WS_METHODS.serverReadCodexResetCredits]: "read",
  [WS_METHODS.serverConsumeCodexResetCredit]: "mutation",
  [WS_METHODS.serverListLocalTasks]: "read",
  [WS_METHODS.serverGetLocalTask]: "read",
  [WS_METHODS.serverCreateLocalTask]: "mutation",
  [WS_METHODS.serverUpdateLocalTask]: "mutation",
  [WS_METHODS.serverDeleteLocalTask]: "mutation",
  [WS_METHODS.serverDelegateLocalTask]: "mutation",
  [WS_METHODS.serverGetDailyRecap]: "read",
  // Re-probes provider status; the result is derived state, not a setting.
  [WS_METHODS.serverRefreshProviders]: "read",
  [WS_METHODS.serverUpdateProvider]: "mutation",
  [WS_METHODS.serverUpdateSettings]: "mutation",
  [WS_METHODS.serverUpsertKeybinding]: "mutation",
  [WS_METHODS.shellOpenInEditor]: "mutation",
  [WS_METHODS.sourceControlAddChangeRequestComment]: "mutation",
  [WS_METHODS.sourceControlAddChangeRequestCommentReaction]: "mutation",
  [WS_METHODS.sourceControlAddIssueComment]: "mutation",
  [WS_METHODS.sourceControlAddIssueCommentReaction]: "mutation",
  [WS_METHODS.sourceControlCloneRepository]: "mutation",
  [WS_METHODS.sourceControlCreateIssue]: "mutation",
  [WS_METHODS.sourceControlGetChangeRequestDetail]: "read",
  [WS_METHODS.sourceControlGetChangeRequestFilesViewed]: "read",
  [WS_METHODS.sourceControlSetChangeRequestFileViewed]: "mutation",
  [WS_METHODS.sourceControlGetChangeRequestDiff]: "read",
  [WS_METHODS.sourceControlGetIssue]: "read",
  [WS_METHODS.sourceControlGetWorkflowJobLog]: "read",
  [WS_METHODS.sourceControlGetWorkflowRunJobs]: "read",
  [WS_METHODS.sourceControlListChangeRequests]: "read",
  [WS_METHODS.sourceControlListIssueAssignees]: "read",
  [WS_METHODS.sourceControlListIssueLabels]: "read",
  [WS_METHODS.sourceControlListIssues]: "read",
  [WS_METHODS.sourceControlListWorkflowRuns]: "read",
  [WS_METHODS.sourceControlLookupRepository]: "read",
  [WS_METHODS.sourceControlMergeChangeRequest]: "mutation",
  [WS_METHODS.sourceControlPublishRepository]: "mutation",
  [WS_METHODS.sourceControlRerunWorkflow]: "mutation",
  [WS_METHODS.sourceControlGetChangeRequestActivity]: "read",
  [WS_METHODS.sourceControlGetChangeRequestFileContents]: "read",
  [WS_METHODS.sourceControlSubmitChangeRequestReview]: "mutation",
  [WS_METHODS.sourceControlReplyToReviewThread]: "mutation",
  [WS_METHODS.sourceControlSetReviewThreadResolved]: "mutation",
  [WS_METHODS.sourceControlUpdateChangeRequestComment]: "mutation",
  [WS_METHODS.sourceControlUpdateChangeRequest]: "mutation",
  [WS_METHODS.sourceControlCreateChangeRequest]: "mutation",
  [WS_METHODS.sourceControlLinkWorktreePullRequest]: "mutation",
  [WS_METHODS.sourceControlDismissWorktreePullRequest]: "mutation",
  [WS_METHODS.sourceControlSearchChangeRequests]: "read",
  [WS_METHODS.sourceControlSearchIssues]: "read",
  [WS_METHODS.sourceControlSearchRepositories]: "read",
  [WS_METHODS.subscribeAuthAccess]: "read",
  [WS_METHODS.subscribeServerConfig]: "read",
  [WS_METHODS.subscribeServerLifecycle]: "read",
  [WS_METHODS.subscribeTerminalEvents]: "read",
  [WS_METHODS.subscribeVcsStatus]: "read",
  [WS_METHODS.terminalClear]: "mutation",
  [WS_METHODS.terminalClose]: "mutation",
  [WS_METHODS.terminalOpen]: "mutation",
  [WS_METHODS.terminalResize]: "mutation",
  [WS_METHODS.terminalRestart]: "mutation",
  [WS_METHODS.terminalWrite]: "mutation",
  [WS_METHODS.textGenerationAskSideQuestion]: "mutation",
  [WS_METHODS.textGenerationCancelSideQuestion]: "mutation",
  [WS_METHODS.textGenerationGenerateBranchName]: "read",
  [WS_METHODS.textGenerationGenerateIssueContent]: "read",
  // Recomputes the derived inbox ranking; nothing the user issued.
  [WS_METHODS.threadPriorityEnsureCurrent]: "read",
  [WS_METHODS.searchThreadMessages]: "read",
  [WS_METHODS.threadsSetManualBucket]: "mutation",
  [WS_METHODS.threadsSetManualPosition]: "mutation",
  [WS_METHODS.vcsCreateRef]: "mutation",
  [WS_METHODS.vcsCreateWorktree]: "mutation",
  [WS_METHODS.vcsInit]: "mutation",
  [WS_METHODS.vcsListRefs]: "read",
  [WS_METHODS.vcsReadLineBlame]: "read",
  [WS_METHODS.vcsReadLocalChanges]: "read",
  [WS_METHODS.vcsApplyIndexPatch]: "mutation",
  [WS_METHODS.vcsReadComparison]: "read",
  [WS_METHODS.vcsPull]: "mutation",
  [WS_METHODS.vcsRefreshStatus]: "read",
  [WS_METHODS.vcsRemoveWorktree]: "mutation",
  [WS_METHODS.vcsSwitchRef]: "mutation",
  [WS_METHODS.workItemsAddComment]: "mutation",
  [WS_METHODS.workItemsEditComment]: "mutation",
  [WS_METHODS.workItemsGet]: "read",
  [WS_METHODS.workItemsList]: "read",
  [WS_METHODS.workItemsListProjects]: "read",
  [WS_METHODS.workItemsListTransitions]: "read",
  [WS_METHODS.workItemsSearch]: "read",
  [WS_METHODS.workItemsTransition]: "mutation",
  [WS_METHODS.workItemsUpdate]: "mutation",
  [WS_METHODS.worktreesSetManualPosition]: "mutation",
} as const satisfies Record<RpcMethod, RpcDeliveryEffect>;

/** Unclassified methods are mutations: delivery uncertainty fails closed. */
export function rpcDeliveryEffectFor(method: string): RpcDeliveryEffect {
  return Object.hasOwn(RPC_DELIVERY_EFFECT_POLICY, method)
    ? RPC_DELIVERY_EFFECT_POLICY[method as RpcMethod]
    : "mutation";
}

const ROLE_ORDER: Readonly<Record<RelayEffectiveRole, number>> = {
  viewer: 1,
  operator: 2,
  owner: 3,
};

export function hostedRoleAllows(
  role: RelayEffectiveRole | null,
  method: string,
  roleStateFresh = true,
): boolean {
  if (!role || !roleStateFresh) return false;
  const required = rpcAccessFor(method);
  if (required === "authenticated" || required === "direct_owner") return false;
  return ROLE_ORDER[role] >= ROLE_ORDER[required];
}
