import {
  AGENT_CONTROL_WS_METHODS,
  CONTEXT_HANDOFF_WS_METHODS,
  DEVICE_WS_METHODS,
  ORCHESTRATION_WS_METHODS,
  WS_METHODS,
  type RelayEffectiveRole,
} from "@ryco/contracts";

export type RpcMethod =
  | (typeof WS_METHODS)[keyof typeof WS_METHODS]
  | (typeof ORCHESTRATION_WS_METHODS)[keyof typeof ORCHESTRATION_WS_METHODS]
  | (typeof CONTEXT_HANDOFF_WS_METHODS)[keyof typeof CONTEXT_HANDOFF_WS_METHODS]
  | (typeof DEVICE_WS_METHODS)[keyof typeof DEVICE_WS_METHODS]
  | (typeof AGENT_CONTROL_WS_METHODS)[keyof typeof AGENT_CONTROL_WS_METHODS];

export type RpcAccess = RelayEffectiveRole | "authenticated" | "direct_owner";

export const RPC_ACCESS_POLICY = {
  [DEVICE_WS_METHODS.read]: "viewer",
  [DEVICE_WS_METHODS.subscribeEvents]: "viewer",
  [DEVICE_WS_METHODS.lifecycle]: "owner",
  [DEVICE_WS_METHODS.input]: "owner",
  [DEVICE_WS_METHODS.app]: "owner",
  [DEVICE_WS_METHODS.recording]: "owner",
  // Agent Control approval decisions authorize agent-requested mutations
  // and the queue exposes prompt summaries and target metadata, so the
  // whole surface is owner-only — including reads and the push stream.
  [AGENT_CONTROL_WS_METHODS.acceptProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.getProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.listProposals]: "owner",
  [AGENT_CONTROL_WS_METHODS.rejectProposal]: "owner",
  [AGENT_CONTROL_WS_METHODS.subscribeProposals]: "owner",
  [AGENT_CONTROL_WS_METHODS.listIntegrations]: "owner",
  [AGENT_CONTROL_WS_METHODS.createIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.updateIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.resumeIntegrationPairing]: "owner",
  [AGENT_CONTROL_WS_METHODS.revokeIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.deleteIntegration]: "owner",
  [AGENT_CONTROL_WS_METHODS.listMcpInstallations]: "owner",
  [AGENT_CONTROL_WS_METHODS.connectMcpInstallation]: "owner",
  [AGENT_CONTROL_WS_METHODS.repairMcpInstallation]: "owner",
  [AGENT_CONTROL_WS_METHODS.disconnectMcpInstallation]: "owner",
  [WS_METHODS.atlassianDisconnect]: "owner",
  [WS_METHODS.atlassianGetProjectLink]: "owner",
  [WS_METHODS.atlassianListConnections]: "owner",
  [WS_METHODS.atlassianListResources]: "owner",
  [WS_METHODS.atlassianRefresh]: "owner",
  [WS_METHODS.atlassianSaveManualBitbucketToken]: "owner",
  [WS_METHODS.atlassianSaveManualJiraToken]: "owner",
  [WS_METHODS.atlassianSaveProjectLink]: "owner",
  [WS_METHODS.atlassianStartOAuth]: "owner",
  [WS_METHODS.chatAttachmentsCreateFileUpload]: "operator",
  [WS_METHODS.chatAttachmentsReadChunk]: "operator",
  [WS_METHODS.filesystemBrowse]: "operator",
  [WS_METHODS.gitArchiveWorktree]: "operator",
  [WS_METHODS.gitCreateWorktreeForProject]: "operator",
  [WS_METHODS.gitDeleteWorktree]: "operator",
  [WS_METHODS.gitFindWorktreeForOrigin]: "operator",
  [WS_METHODS.gitPreparePullRequestThread]: "operator",
  [WS_METHODS.gitResolvePullRequest]: "operator",
  [WS_METHODS.gitRestoreWorktree]: "operator",
  [WS_METHODS.gitRunStackedAction]: "operator",
  [WS_METHODS.keybindingsReplaceCustom]: "owner",
  [WS_METHODS.mcpListServers]: "owner",
  [WS_METHODS.mcpListWorkspaces]: "owner",
  [WS_METHODS.mcpReloadServers]: "owner",
  [WS_METHODS.mcpRemoveServer]: "owner",
  [WS_METHODS.mcpSetServerEnabled]: "owner",
  [WS_METHODS.mcpStartOauthLogin]: "owner",
  [WS_METHODS.mcpUpsertServer]: "owner",
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: "operator",
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: "viewer",
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: "viewer",
  // File-content reads match projectsReadFile/filesystemBrowse: operator,
  // not viewer — scripts and task outputs can carry prompts and secrets.
  [ORCHESTRATION_WS_METHODS.getTaskOutput]: "operator",
  [ORCHESTRATION_WS_METHODS.getThreadHistoryPage]: "viewer",
  [ORCHESTRATION_WS_METHODS.getThreadWindow]: "viewer",
  [ORCHESTRATION_WS_METHODS.getWorkflowScript]: "operator",
  [ORCHESTRATION_WS_METHODS.stopBackgroundTask]: "operator",
  [ORCHESTRATION_WS_METHODS.replayEvents]: "viewer",
  [ORCHESTRATION_WS_METHODS.replayEventsPage]: "viewer",
  [ORCHESTRATION_WS_METHODS.searchThreadMessages]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeShell]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeThread]: "viewer",
  [ORCHESTRATION_WS_METHODS.subscribeThreadWindow]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.getInspectionSummary]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.listInspectionEntries]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.readRawPayloadChunk]: "viewer",
  [CONTEXT_HANDOFF_WS_METHODS.readExportChunk]: "viewer",
  [WS_METHODS.projectsAdd]: "operator",
  [WS_METHODS.projectsInitializeGit]: "operator",
  [WS_METHODS.projectsList]: "viewer",
  [WS_METHODS.projectsListEntries]: "operator",
  [WS_METHODS.projectsReadFile]: "operator",
  [WS_METHODS.projectsReadIcon]: "viewer",
  [WS_METHODS.projectsReadFileBinary]: "operator",
  [WS_METHODS.projectsRemove]: "operator",
  [WS_METHODS.projectsSearchEntries]: "operator",
  [WS_METHODS.projectsStageFileReference]: "operator",
  [WS_METHODS.projectsWriteFile]: "operator",
  [WS_METHODS.serverCheckOpinionatedPlugins]: "owner",
  [WS_METHODS.serverDiscoverSourceControl]: "owner",
  [WS_METHODS.serverGetAdvertisedEndpoints]: "viewer",
  [WS_METHODS.serverGetConfig]: "viewer",
  [WS_METHODS.serverGetDiagnosticsMetrics]: "owner",
  [WS_METHODS.serverGetDiagnosticsSnapshot]: "owner",
  [WS_METHODS.serverSignalDiagnosticProcess]: "owner",
  [WS_METHODS.serverGetResourceTelemetryHistory]: "owner",
  [WS_METHODS.serverRetryResourceTelemetry]: "owner",
  [WS_METHODS.serverGetSettings]: "viewer",
  [WS_METHODS.serverGetStatistics]: "owner",
  [WS_METHODS.serverGetUsageSummary]: "owner",
  [WS_METHODS.serverInstallOpinionatedPlugin]: "owner",
  [WS_METHODS.serverListOpinionatedPlugins]: "owner",
  [WS_METHODS.serverRefreshProviders]: "owner",
  [WS_METHODS.serverUpdateProvider]: "owner",
  [WS_METHODS.serverUpdateSettings]: "owner",
  [WS_METHODS.serverUpsertKeybinding]: "owner",
  [WS_METHODS.shellOpenInEditor]: "operator",
  [WS_METHODS.sourceControlAddChangeRequestComment]: "operator",
  [WS_METHODS.sourceControlAddChangeRequestCommentReaction]: "operator",
  [WS_METHODS.sourceControlAddIssueComment]: "operator",
  [WS_METHODS.sourceControlAddIssueCommentReaction]: "operator",
  [WS_METHODS.sourceControlCloneRepository]: "operator",
  [WS_METHODS.sourceControlCreateIssue]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestDetail]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestFilesViewed]: "operator",
  [WS_METHODS.sourceControlSetChangeRequestFileViewed]: "operator",
  [WS_METHODS.sourceControlGetChangeRequestDiff]: "operator",
  [WS_METHODS.sourceControlGetIssue]: "operator",
  [WS_METHODS.sourceControlGetWorkflowJobLog]: "operator",
  [WS_METHODS.sourceControlGetWorkflowRunJobs]: "operator",
  [WS_METHODS.sourceControlListChangeRequests]: "operator",
  [WS_METHODS.sourceControlListIssueAssignees]: "operator",
  [WS_METHODS.sourceControlListIssueLabels]: "operator",
  [WS_METHODS.sourceControlListIssues]: "operator",
  [WS_METHODS.sourceControlListWorkflowRuns]: "operator",
  [WS_METHODS.sourceControlLookupRepository]: "operator",
  [WS_METHODS.sourceControlMergeChangeRequest]: "operator",
  [WS_METHODS.sourceControlPublishRepository]: "operator",
  [WS_METHODS.sourceControlRerunWorkflow]: "operator",
  [WS_METHODS.sourceControlSearchChangeRequests]: "operator",
  [WS_METHODS.sourceControlSearchIssues]: "operator",
  [WS_METHODS.sourceControlSearchRepositories]: "operator",
  [WS_METHODS.subscribeAuthAccess]: "direct_owner",
  [WS_METHODS.subscribeServerConfig]: "viewer",
  [WS_METHODS.subscribeServerLifecycle]: "viewer",
  [WS_METHODS.subscribeTerminalEvents]: "operator",
  [WS_METHODS.subscribeVcsStatus]: "operator",
  [WS_METHODS.terminalClear]: "operator",
  [WS_METHODS.terminalClose]: "operator",
  [WS_METHODS.terminalOpen]: "operator",
  [WS_METHODS.terminalResize]: "operator",
  [WS_METHODS.terminalRestart]: "operator",
  [WS_METHODS.terminalWrite]: "operator",
  [WS_METHODS.textGenerationAskSideQuestion]: "operator",
  [WS_METHODS.textGenerationCancelSideQuestion]: "operator",
  [WS_METHODS.textGenerationGenerateBranchName]: "operator",
  [WS_METHODS.textGenerationGenerateIssueContent]: "operator",
  [WS_METHODS.threadPriorityEnsureCurrent]: "operator",
  [WS_METHODS.searchThreadMessages]: "owner",
  [WS_METHODS.threadsSetManualBucket]: "operator",
  [WS_METHODS.threadsSetManualPosition]: "operator",
  [WS_METHODS.vcsCreateRef]: "operator",
  [WS_METHODS.vcsCreateWorktree]: "operator",
  [WS_METHODS.vcsInit]: "operator",
  [WS_METHODS.vcsListRefs]: "operator",
  [WS_METHODS.vcsPull]: "operator",
  [WS_METHODS.vcsRefreshStatus]: "operator",
  [WS_METHODS.vcsRemoveWorktree]: "operator",
  [WS_METHODS.vcsSwitchRef]: "operator",
  [WS_METHODS.workItemsAddComment]: "operator",
  [WS_METHODS.workItemsEditComment]: "operator",
  [WS_METHODS.workItemsGet]: "viewer",
  [WS_METHODS.workItemsList]: "viewer",
  [WS_METHODS.workItemsListProjects]: "viewer",
  [WS_METHODS.workItemsListTransitions]: "viewer",
  [WS_METHODS.workItemsSearch]: "viewer",
  [WS_METHODS.workItemsTransition]: "operator",
  [WS_METHODS.workItemsUpdate]: "operator",
  [WS_METHODS.worktreesSetManualPosition]: "operator",
} as const satisfies Record<RpcMethod, RpcAccess>;

export function rpcAccessFor(method: string): RpcAccess {
  if (!Object.hasOwn(RPC_ACCESS_POLICY, method)) {
    throw new Error("RPC method has no explicit access classification.");
  }
  return RPC_ACCESS_POLICY[method as RpcMethod];
}

const ROLE_ORDER: Readonly<Record<RelayEffectiveRole, number>> = {
  viewer: 1,
  operator: 2,
  owner: 3,
};

export function hostedRoleAllows(
  role: RelayEffectiveRole | null,
  method: string,
  roleStateFresh = true,
): boolean {
  if (!role || !roleStateFresh) return false;
  const required = rpcAccessFor(method);
  if (required === "authenticated" || required === "direct_owner") return false;
  return ROLE_ORDER[role] >= ROLE_ORDER[required];
}
